# Generated by Django 4.1.13 on 2024-05-31 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='api_token',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
