# Generated by Django 4.1.13 on 2024-05-31 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(max_length=255, unique=True)),
                ('job_name', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('job_full_text', models.TextField()),
                ('post_url', models.URLField()),
                ('post_apply_url', models.URLField()),
                ('company_url', models.URLField(null=True)),
                ('company_industry', models.CharField(max_length=255, null=True)),
                ('minimum_compensation', models.CharField(max_length=50, null=True)),
                ('maximum_compensation', models.CharField(max_length=50, null=True)),
                ('compensation_type', models.CharField(max_length=50, null=True)),
                ('job_hours', models.CharField(max_length=50, null=True)),
                ('role_seniority', models.CharField(max_length=50, null=True)),
                ('minimum_education', models.CharField(blank=True, max_length=255, null=True)),
                ('office_location', models.CharField(max_length=255, null=True)),
                ('post_html', models.TextField(null=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('region', models.CharField(max_length=100, null=True)),
                ('country', models.CharField(max_length=100, null=True)),
                ('job_published_at', models.DateTimeField(null=True)),
                ('last_indexed', models.DateTimeField()),
                ('ngrams', models.TextField()),
            ],
        ),
    ]
